openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /devices/:
    get:
      operationId: list_devices_devices__get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DeviceRead'
                type: array
          description: Successful Response
      summary: List Devices
      tags:
      - Devices
    post:
      operationId: add_device_devices__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCreate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceRead'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add Device
      tags:
      - Devices
  /rooms/:
    get:
      operationId: list_rooms_rooms__get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/RoomRead'
                type: array
          description: Successful Response
      summary: List Rooms
      tags:
      - Rooms
    post:
      operationId: add_room_rooms__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomCreate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomRead'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add Room
      tags:
      - Rooms
  /turnoff/:
    post:
      operationId: turn_off_device_turnoff__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCreate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceRead'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Turn Off Device
      tags:
      - Toggle Device
  /turnon/:
    post:
      operationId: turn_on_device_turnon__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCreate'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceRead'
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Turn On Device
      tags:
      - Toggle Device
components:
  schemas:
    DeviceCreate:
      example:
        room_id: 0
        name: name
      properties:
        name:
          title: Name
          type: string
        room_id:
          title: Room Id
          type: integer
      required:
      - name
      - room_id
      title: DeviceCreate
    DeviceRead:
      example:
        room_id: 6
        room_name: room_name
        name: name
        id: 0
        state: true
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
        room_id:
          title: Room Id
          type: integer
        room_name:
          title: Room Name
          type: string
        state:
          title: State
          type: boolean
      required:
      - id
      - name
      - room_id
      - state
      title: DeviceRead
    HTTPValidationError:
      example:
        detail:
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
        - msg: msg
          loc:
          - ValidationError_loc_inner
          - ValidationError_loc_inner
          type: type
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: detail
          type: array
      title: HTTPValidationError
    RoomCreate:
      example:
        name: name
      properties:
        name:
          title: Name
          type: string
      required:
      - name
      title: RoomCreate
    RoomRead:
      example:
        name: name
        id: 0
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
      required:
      - id
      - name
      title: RoomRead
    ValidationError:
      example:
        msg: msg
        loc:
        - ValidationError_loc_inner
        - ValidationError_loc_inner
        type: type
      properties:
        loc:
          items:
            $ref: '#/components/schemas/ValidationError_loc_inner'
          title: loc
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ValidationError_loc_inner:
      anyOf:
      - type: string
      - type: integer
      title: ValidationError_loc_inner
